require 'rake/testtask'
Rake::TestTask.new do |t|
  t.pattern = 'test/*_test.rb'
end

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new do |t|
  t.pattern = 'spec/**/*_spec.rb'
end

task :default => :spec
