version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 0
    labels:
      - "deps"
    versioning-strategy: "increase"
    rebase-strategy: "disabled"
